.eslintrc
.travis.yml
Gruntfile.js
package.json

Our travis ci builds were failing because we didn't have a .travis.yml file.
This PR adds the travis config. It also adds eslint checks using this configs rules by inheriting index.js in the eslintrc file.  To facilitate the eslint check, grunt was also added with the corresponding Gruntfile.

Add Travis Config, eslint and grunt

---

.eslintrc
.travis.yml
Gruntfile.js
index.js
node.js
package.json

The comma-dangle rule was set to only-multiline. This setting does not require a comma in multi-line, it only disallows a trailing comma in single line objects and arrays.
I changed the setting to always-multiline to better fit our coding standards.

Fix comma-dangle to require comma in multiline arrays and objects

---

index.js

Our standards state that there is a space at
the beginning of each comment, but the corresponding
ESLint rule was never enabled.
This adds `'spaced-comment': [ 'error', 'always' ]` to
our config.

Add rule to require space before comment

---

index.js
package-lock.json
package.json

To support linting TypeScript with ESLint, we need to use a special
parser to tell ESLint how to parse the TypeScript files. We also need to
override some rules that have problems with TypeScripts special syntax.
In addition, in order to use ES6+ features in our code, we need to
enable the correct parser options and allow some previously banned
syntax.
This commit addresses these 2 concerns by adding the TypeScript parser
and adjusting our index.js rules to allow ES6+.

Add configuration for TypeScript and allow ES6+ features

---

index.js
package-lock.json
package.json

Various rules were added to the our ESLint plugin, including a new fork of the indent rule. 
This PR has the necessary package bump to use it. It also includes the addition of a peerDependency on ESLint@5.x. The plugin's new fork of the indent rule requires at least version 5 of ESLint in order to use the ASTUtil. 
In addition, `quote-props` has been turned off since we no longer support ES3 in our codebases and that rule is not needed after ES5.

Update @silvermine/eslint-plugin-silvermine to version 2.0.0

---

index.js
package-lock.json
package.json

A new option on the base eslint indent rule fixes the problem that
forced us to make a custom rule. We can now line up variable
declarations by using the "VariableDeclarator": "first" option.
To use this rule, we need to ensure a peer dependency of
eslint >= 5.11.1. Also, `grunt-eslint` needed to be re-installed to
update it's eslint dependency in the package-lock.json file (the same
version was used, but the eslint dependency pulled down the new version)

Remove silvermine/indent rule and use base eslint indent rule

---

index.js
package-lock.json
package.json

Upgrading the typescript plugin fixes #29 and a lot of edge cases that we haven't hit yet.

Upgrade eslint-plugin-typescript to 1.0.0-rc.2

---

index.js

In TypeScript, `type` definitions are hoisted, so it is valid to
reference a type that is declared later on in the file. We want to allow
this so that we can organize the types in a given file hierarchically.

Fixes #36 Allow use of typedefs before they are defined

---

index.js

The standard ESLint `no-dupe-class-members` rule will report false
positives for overloaded TypeScript class methods. This rule is safe to
disable because actual duplicate class members will be caught by the
TypeScript compiler.

Fixes #34 Disable no-dupe-class-members for TypeScript files

---

index.js
package-lock.json
package.json

The `eslint-plugin-typescript` project has been moved to
`@typescript-eslint/eslint-plugin` and the old repo has been deprecated.
Related projects such as the TypeScript ESLint parser have also been
moved to the `@typescript-eslint` namespace: https://eslint.org/blog/2019/01/future-typescript-eslint

Fixes #38 Use new @typescript-eslint projects

---

index.js

Originally, the TypeScript no-unused-vars rule relied on the base
no-unused-vars rule to be on. This was changed in a later commit and now
we are receiving double errors for unused vars.
This commit turns of the base no-unused-vars rule for TypeScript files.

Fixes #41 Turn off base no-unused-vars for TypeScript files

---

.gitignore
.travis.yml
index.js
package-lock.json
package.json
partials/vue.js

NOTE: This is a draft PR and still needs an updated `eslint-plugin` in the dependencies.
Updated packages and eslint rules to support TypeScript 4 and eslint 8.
Updated packages for linting Vue 3, most notably:
* Support for compiler macros. 
* [vue/multi-word-component-names](https://eslint.vuejs.org/rules/multi-word-component-names.html) turned off since we do have components that have single-word names. If we left this on, we would need to refactor for all our single-word components.
* [vue/v-on-event-hyphenation](https://eslint.vuejs.org/rules/v-on-event-hyphenation.html) is on, as most of our code follows this convention.

Update for TypeScript 4, Vue 3, eslint 8

---

package-lock.json
package.json

By putting @silvermine/eslint-plugin-silvermine in `dependencies` and not `devDependencies`, this package can be pulled into a project without needing to explicitly include eslint-plugin-silvermine as well.

Put @silvermine/eslint-plugin-silvermine in main dependencies

---

partials/vue.js

The vue/multi-word-component-names rule is applied to both Vue 2 and Vue 3 versions of the eslint-plugin-vue package for essential, recommended, and strongly recommended rule sets. So, when we disable this rule, it should be for both Vue 2 and Vue 3.
Ref: https://eslint.vuejs.org/rules/multi-word-component-names.html

fix: vue/multi-word-component-names should be universal

---

index.js
test-cases/typescript/SmallClass.ts
test-cases/typescript/TestClass.ts

- Adds additional enforcements for read-only constants
- Allows PascalCase for function arguments that are class constructors
- Allows PascalCase for variables assigned to class constructors
Closes #92

feat: fine tune naming conventions

---

index.js

On 12/5/22 [invalid values for @typescript-eslint/member-ordering were removed](https://github.com/typescript-eslint/typescript-eslint/pull/6164/files) that we have maintained in our config. This removes the invalid values related to
"private" abstract class members. Obviously, a private member in a class cannot be an abstract field. 😂

fix: remove invalid member-ordering value

---

.gitignore
index.js
partials/base.js
partials/ignores.js

In the transition to flat config, I didn't notice this detail [from the 8.57 docs](https://eslint.org/docs/v8.x/use/configure/configuration-files-new#globally-ignoring-files-with-ignores):
> If ignores is used **without any other keys in the configuration object,** then the patterns act as global ignores.
Ignores were previously added inside a configuration object that was shared with other properties, so ESLint did not apply them globally.
This PR breaks ignores out into their own file. By keeping ignores in their own file, we will hopefully avoid a similar mistake in the future.
This also removes a DS_Store file and ignores like files.

fix: default ignores

---

package-lock.json
package.json

This has no side-effect since the plugin is not used up to now. The following PRs will receive the configs to gradually migrate to it for all possible rules.

chore: upgrade @stylistic/eslint-plugin to 3.0.1

---

partials/base.js

https://github.com/silvermine/eslint-config-silvermine/pull/111
https://github.com/silvermine/eslint-config-silvermine/pull/115
We majorly allow the last element of an enum to have a trailing comma, so, for that reason, this PR specifically defines this as one our rule behaviors. This rule was not enforced for ts syntax, so now that it is, some little changes are needed in the projects that use it

config: migrate comma-dangle to stylistic

---

partials/base.js

https://github.com/silvermine/eslint-config-silvermine/pull/111
https://github.com/silvermine/eslint-config-silvermine/pull/115
This has a PR to itself just because this rule caused many changes when applied, but there is not really a change to it besides being migrated to stylistic.

config: migrate max-len to stylistic

---

partials/base.js

#115 
After migrating these rules to stylistic, these rules didn't raise any linting errors in the project the changes were tested. I doesn't mean that this will be the case for every project, but based in my testing sample, the likelyhood is lower.

config: migrate to stylistic eslint rules without observed impact 

---

partials/base.js

#115 
After migrating these rules to stylistic, the project where they were tested started raising lint errors. So I've put them together to possibly bring them to attention, but it doesn't mean that these rules will raise errors for all projects.

config: migrate to stylistic eslint rules with observed impact

---

partials/base.js

https://github.com/silvermine/eslint-config-silvermine/pull/111
https://github.com/silvermine/eslint-config-silvermine/pull/115
Base partial doen’t specify typescript specific rules, so the indent rule didn’t support typescript syntax. Now that we use the unified stylistic eslint plugin, this rule correctly support ts and js syntaxes by default, so some changes in behavior may be noticed. 
Since this rule was defined using only eslint, not typescript-eslint, in some cases it was not being validated. 
Also, [this rule is known to be broken](https://github.com/typescript-eslint/typescript-eslint/issues/1824) (currently, the docs reference this same issue: https://eslint.style/rules/default/indent#ts-indent), even more for ts syntax. 
For those reasons, some places may start to raise errors. …

config: migrate indent to stylistic
